config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  resources :articles do 
    resource :like, module: :articles
  end
  resources :comments
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy] 
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :likes

  scope :sorted, -> {order("created_at DESC")}

  validates :title, presence: true, length: {minimum: 5, maximum: 100}
  validates :description, presence:true, length: {minimum: 10}
  validates :user_id, presence: true

  has_attached_file :image, styles: { medium: "640x350>", thumb: "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  acts_as_commentable

end

app/controllers/articles/likes_controller.rb
class Articles::LikesController < ApplicationController
  before_action :require_user
  before_action :set_article

  def create
    @article.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def destroy
    @article.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  private

    def set_article
      @article = Article.find(params[:article_id])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, :only => [:show, :edit, :update, :destroy]
  before_action :require_user, :except => [:index, :show]
  before_action :require_same_user, :only => [:edit, :update, :destroy]
  
  def index
    @q = Article.search(params[:q])
    @articles = @q.result.sorted.page(params[:page]).per_page(5)
  end

  def show
    if logged_in?
      @new_comment = Comment.build_from(@article, current_user.id, "")
    else
      @all_comments = @article.comment_threads
    end
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)    
    if @article.save
      flash[:success] = 'Article was successfully created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update_attributes(article_params)
      flash[:success] = "Article was updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
    flash[:danger] = "Article was deleted"
  end

  private

    def find_article
      @article = Article.find(params[:id])  
    end

    def article_params
      params.require(:article).permit(:title, :description, :user_id, :image, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can edit or delete only your article"
        redirect_to root_path
      end
    end

end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-meta">          
          <p class="date">Published by: <%= article.user.username if article.user %> on <%= "#{article.created_at.to_time.strftime('%B %e at %l:%M %p')}" %> </p>          
        </div>
        <div class="article-body">
          <div class="truncate">
            <%= article.description.truncate(100) %>
          </div>
          <% if article.image? %>            
            <h2 class="left teal-text"><i class="fa fa-picture-o fa-1x"></i></h2>
          <% end -%>
          <p class="comment_count" style="float: right"><i class="fa fa-comments" aria-hidden="true"></i> <%= article.comment_threads.count %></p><br>
          <br><p id="article_<%= article.id %>_likes" style="float: right"><%= render partial: "articles/likes", locals: { article: article } %></p>
        </div>
        
        <br>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end -%>
      </div>
    </div>
  </div>
<% end -%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
	<div class="col-md-12">
		<%= form_for(@article, :html => {multipart:true, class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :image %><br>
				</div>			
				<div class="col-sm-2">
					<%= f.file_field :image %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :title %><br>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :description %>
				</div>
				<div class="col-sm-8">
					<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article" %>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-sm-offset-2 col-sm-8">
						<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
							<% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text}%>
						<% end -%>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-10 col-sm-offset-2">
					<%= f.submit class:"btn btn-success btn-lg"%>
				</div>
			</div>
		<% end -%>
	</div>
</div>

app/views/articles/_likes.html.erb
<% if logged_in? && current_user.likes?(article) %>
  <%= link_to article_like_path(article), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true"></i>
  <% end -%>
<% else %>
  <%= link_to article_like_path(article), method: :post, remote: true do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
  <% end -%>
<% end -%>

<%= article.likes.count %>
<% article.likes.last(5).each do |like| %>
  <%= image_tag like.user.avatar.url, width: 20, class:"img-circle" %>
<% end -%>

app/views/articles/edit.html.erb
<h1 align="center">Edit Article</h1>

<%= render 'form'%>
<div class="col-xs-4 col-xs-offset-5">
  [ <%= link_to "Cancel Edit and return to Article", article_path(@article)%> ]
</div>

app/views/articles/index.html.erb
<h2 align="center">All Articles</h2>
<div class="pull-right">
  <%= search_form_for @q, html: {class: "form-inline"} do |f| %>    
    <%= f.search_field :title_or_description_cont, placeholder: "Search...", class: "form-control" %>
    <button type="submit" class="btn btn-default">Submit</button>    
  <% end -%>
</div>
<br>

<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate previous_label: "Previous", next_label: "Next" %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create a new Article</h1>

<%= render 'form'%>
<div class="col-xs-4 col-xs-offset-5">
  [ <%= link_to "Cancel Create and return to Articles", articles_path %> ]
</div>

app/views/articles/show.html.erb
<h2 align="center"> <%= @article.title %></h2>
<div class="well col-xs-10 col-xs-offset-1">
  <ul class="listing">
      <div class="row">
        <div align="center">
          <li><%= image_tag @article.user.avatar.url, size:150, class:"img-circle" %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user)%>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <div class="image">
    <center><%= image_tag @article.image.url(:medium) if @article.image? %></center>
  </div>
  <p class="date">Published on <%= @article.created_at.to_time.strftime('%B %e at %l:%M %p') %></p>  
  <%= markdown(@article.description) %>
  <hr>
  <%if @article.categories.any? %>
    <p>Categories: <%= render @article.categories%></p>
  <% end -%>
  <div id="article_<%= @article.id %>_likes">    
    <%= render partial: 'likes', locals: { article: @article } %>
  </div>
  <div class="article-actions">    
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>      
        <%= link_to "Edit", edit_article_path(@article), 
          class: "article-btn"%>    
        <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are You Sure?"}, class: "article-btn"%>      
    <% end -%>
  </div>  
  <%= render partial: "comments/template", locals: {commentable: @article, new_comment: @comment} %>  
</div>