config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  resources :articles do 
    resource :like, module: :articles
  end
  resources :comments
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy] 
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 30}
  validates_uniqueness_of :name

  scope :sorted, -> {order("created_at DESC")}

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_catgory, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]
  def index
    @categories = Category.sorted.page(params[:page]).per_page(5)
  end

  def show    
    @category_articles = @category.articles.reorder("updated_at DESC").paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created successfully "
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit    
  end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private

    def find_catgory
      @category = Category.find(params[:id])   
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? and !current_user.admin?)
        flash[:danger] = "Only admin can perform that action"
        redirect_to categories_path
      end
    end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category)%> &nbsp; </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %><br>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <%= f.submit class: "btn btn-success btn-lg"%>
    </div>
  </div>
<% end -%>

<div align="center">
  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">All Categories</h1>
<div align="center">  
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li><small><%= pluralize(category.articles.count, "article") %></small></li>
        </div>
      </div>
    </ul>  
  <% end -%>
  <%= will_paginate previous_label: "Previous", next_label: "Next" %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h2 align="center"><%= @category.name %></h2>
<div align="center">  
  <% if logged_in? and current_user.admin? %>
    <div class="row">
      <br>
      <%= link_to "Edit Category Name", edit_category_path(@category), class: "category-btn"%>
    </div>
  <% end -%>
  <br>
  <%= will_paginate @category_articles %>

  <%= render 'articles/article', obj: @category_articles %>

  <%= will_paginate @category_articles%>
</div>