config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  resources :articles do 
    resource :like, module: :articles
  end
  resources :comments
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy] 
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <span class="err_msg">
      <% flash.each do |name, msg|%>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end -%>
    </span>
    <script>
      setTimeout("$('.err_msg').fadeOut('slow')", 5000)
    </script>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand", id: "logo" do %>
        Blog
      <% end %>      
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">      
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li><%= link_to "New Article", new_article_path %></li>
        <% end -%>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        
          <%= yield :right_nav %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></i>Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Categores", categories_path %></li>
              <% Category.all.each do |category|%>
                <li><%= link_to "#{category.name}", category_path(category)%></li>
              <% end -%>
              <% if logged_in? and current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create New Category", new_category_path %></li>
              <% end -%>
            </ul>
          </li>        
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <%= yield :right_nav %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag current_user.avatar.url, size:20, class:"img-circle" %> <%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>              
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css?family=Lato|Roboto" rel="stylesheet"> 
  </head>

  <body>
    
    <%= render 'layouts/navigation'%>
  	<%= render 'layouts/messages' %>
    <%= yield %>    
  </body>
</html>